apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadzeto8356-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadzeto8356-tenant-component
    app.kubernetes.io/part-of: loadzeto8356-tenant-app
  name: loadzeto8356-tenant-component
  namespace: loadzeto8356-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadzeto8356-tenant-component
    weight: null
status: {}
