apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadzeto8356-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadzeto8356-tenant-component
    app.kubernetes.io/part-of: loadzeto8356-tenant-app
  name: loadzeto8356-tenant-component
  namespace: loadzeto8356-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadzeto8356-tenant-component
status:
  loadBalancer: {}
